### ISSUE TITLE
Can you set up 'openvpn' connection?

### ISSUE THREAD

**Issue by izmoxkawaii** [GovernmentPlates/SimpleConnect#1]
auto vpn connect 'openvpn'

**Comment by GovernmentPlates** [comment]
Hi @izmoxkawaii, could you please elaborate your question?

**Comment by izmoxkawaii** [comment]
I mean, does this support openvpn? and tell me what is required for openvpn connection?
C:\Program Files (x86)\Cisco\Cisco AnyConnect Secure Mobility Client <<<<<<<<<<<
Can I use openvpn or any other vpn instead?

**Comment by GovernmentPlates** [comment]
> I mean, does this support openvpn? and tell me what is required for openvpn connection?

This application is designed for Cisco AnyConnect and not OpenVPN.
